name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      plugin-version:
          description: "plugins version"
          required: false
          type: string
  push:
    branches:
      - master
      - main
      - releases/*
      - develop
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-main
  cancel-in-progress: true

jobs:
  tests:
    name: Execute tests
    uses: ./.github/workflows/workflow-test.yml
    with:
      report-status: false

  release:
    name: Release
    needs: [tests]
    if: "!startsWith(github.ref, 'refs/heads/releases')"
    uses: ./.github/workflows/workflow-release.yml
    with:
        plugin-version: ${{ inputs.plugin-version != '' && inputs.plugin-version || (github.ref == 'refs/heads/develop' && 'LATEST-SNAPSHOT' || 'LATEST') }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_GPG_KEYID: ${{ secrets.SONATYPE_GPG_KEYID }}
      SONATYPE_GPG_PASSWORD: ${{ secrets.SONATYPE_GPG_PASSWORD }}
      SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}
      GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
      SLACK_RELEASES_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_WEBHOOK_URL }}
  end:
    runs-on: ubuntu-latest
    needs:
      - release
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Trigger EE Workflow
        uses: peter-evans/repository-dispatch@v3
        if: github.ref == 'refs/heads/develop' && needs.release.result == 'success'
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          repository: kestra-io/kestra-ee
          event-type: "oss-updated"


      # Slack
      - name: Slack - Notification
        uses: Gamesight/slack-workflow-status@master
        if: ${{ always() && env.SLACK_WEBHOOK_URL != 0 }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: GitHub Actions
          icon_emoji: ":github-actions:"
          channel: "C02DQ1A7JLR" # _int_git channel
